### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by bzg** [ia-flash/frontend#5]
I suggest using the [Apache 2.0 license](https://fr.wikipedia.org/wiki/Licence_Apache). Let me know if you want me to make a PR.

**Comment by cristianpb** [comment]
Thank you for the issue. 

Solved in 58e0a1bd51cfdc397b09f27827d1839b575bdfb1 and 68a0220138d1b590870d4bb5604987b198232f55

**Comment by bzg** [comment]
Great, thank you very much!
